# Generated by Django 5.0.3 on 2024-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yerbas',
            fields=[
                ('yerba_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('price_pu', models.IntegerField()),
                ('dost_ilosc', models.IntegerField()),
                ('foto', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
